services:  # 여기서부터 각 컨테이너 정의 시작

  node-backend:  # Node.js 백엔드 서버
    build: ./BackEnd
    ports:
      - "3000:3000"
    volumes:
      - ./BackEnd:/app
      - ./data:/data
    env_file:
      - ./BackEnd/.env
    environment:
      - REDIS_URL=redis://redis:6379   # ✅ 여기만 추가
    depends_on:
      - redis

  # fastapi-ai:
  #   build: ./BackEnd_AI
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./BackEnd_AI:/app

  redis:
    image: redis:8.0.3
    ports:
      - "6379:6379"
