version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./BackEnd/.env
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./FrontEnd_Closet
      dockerfile: Dockerfile.front
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
